"""Add announcement model

Revision ID: 124868bf0ef0
Revises: 03e2ffa2e51c
Create Date: 2025-05-13 16:07:24.617887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124868bf0ef0'
down_revision = '03e2ffa2e51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement')
    # ### end Alembic commands ###
